### ISSUE TITLE
Codegen sometimes fails on Travis CI.

### ISSUE THREAD

**Issue by hbowden** [DigitalRiver/react-atlas#400]
```
> react-atlas-dev@ bootstrap /home/travis/build/DigitalRiver/react-atlas
> npm run lerna:init && npm run lerna:bootstrap && npm run codegen && npm run packages:build
> react-atlas-dev@ lerna:init /home/travis/build/DigitalRiver/react-atlas
> lerna init
lerna info version 2.4.0
lerna info Updating package.json
lerna info Updating lerna.json
lerna info Creating packages directory
lerna success Initialized Lerna files
> react-atlas-dev@ lerna:bootstrap /home/travis/build/DigitalRiver/react-atlas
> lerna bootstrap
lerna info version 2.4.0
lerna info Bootstrapping 5 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna info lifecycle postinstall
lerna info lifecycle prepublish
lerna info lifecycle prepare
lerna success Bootstrapped 5 packages
> react-atlas-dev@ codegen /home/travis/build/DigitalRiver/react-atlas
> node packages/react-atlas/src/codegen.js
Linking: /home/travis/build/DigitalRiver/react-atlas/packages/react-atlas-core/src/Accordion/README.md -> /home/travis/build/DigitalRiver/react-atlas/packages/react-atlas/src/components/Accordion/README.md
fs.js:1090
 return binding.link(pathModule._makeLong(existingPath),
 ^
Error: ENOENT: no such file or directory, link '/home/travis/build/DigitalRiver/react-atlas/packages/react-atlas/src/../../react-atlas-core/src/Accordion/README.md' -> '/home/travis/build/DigitalRiver/react-atlas/packages/react-atlas/src/components/Accordion/README.md'
 at Error (native)
 at Object.fs.linkSync (fs.js:1090:18)
 at createComponentDirectories (/home/travis/build/DigitalRiver/react-atlas/packages/react-atlas/src/codegen.js:305:10)
 at Object.<anonymous> (/home/travis/build/DigitalRiver/react-atlas/packages/react-atlas/src/codegen.js:311:1)
 at Module._compile (module.js:570:32)
 at Object.Module._extensions..js (module.js:579:10)
 at Module.load (module.js:487:32)
 at tryModuleLoad (module.js:446:12)
 at Function.Module._load (module.js:438:3)
 at Module.runMain (module.js:604:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-atlas-dev@ codegen: `node packages/react-atlas/src/codegen.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-atlas-dev@ codegen script.
npm ERR!35m This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR! /home/travis/.npm/_logs/2017-10-23T15_27_56_583Z-debug.log
npm ERR! Linux 4.11.6-041106-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v6.11.4/bin/node" "/home/travis/.nvm/versions/node/v6.11.4/bin/npm" "run" "bootstrap"
npm ERR! node v6.11.4
npm ERR! npm v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! react-atlas-dev@ bootstrap: `npm run lerna:init && npm run lerna:bootstrap && npm run codegen && npm run packages:build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-atlas-dev@ bootstrap script 'npm run lerna:init && npm run lerna:bootstrap && npm run codegen && npm run packages:build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-atlas-dev package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! npm run lerna:init && npm run lerna:bootstrap && npm run codegen && npm run packages:build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs react-atlas-dev
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls react-atlas-dev
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR! /home/travis/build/DigitalRiver/react-atlas/npm-debug.log```

**Comment by Magneticmagnum** [comment]
Do we know why this happens?

**Comment by hbowden** [comment]
Some sort of permission problem. I will have to add some console.logs to the codegen code so we can get a better idea of whats happening.

**Comment by hbowden** [comment]
Doesn't seem to be fixed, reopening.

**Comment by hbowden** [comment]
Appears to be fixed.

**Comment by hbowden** [comment]
Actually it's still happens.

**Comment by hbowden** [comment]
Removing codegen in the near future, so closing, because no longer relevant.
